[workspace]
resolver = "3"
members = ["crates/terra-types", "crates/terra-state", "crates/terra-control", "crates/terra-mobile", "crates/terra-mapping", "crates/terra-transport"]
exclude = ["simulator"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
terra-types = { path = "crates/terra-types" }
terra-state = { path = "crates/terra-state" }
terra-control = { path = "crates/terra-control" }
terra-mapping = { path = "crates/terra-mapping" }
terra-transport = { path = "crates/terra-transport" }
uniffi = "=0.31.1"

[profile.dev]
debug = 0
[profile.release]
lto = "thin"
codegen-units = 1
