[workspace]
resolver = "3"
members = ["crates/terra-actuators", "crates/terra-autonomy", "crates/terra-navigation", "crates/terra-experiment", "crates/terra-types", "crates/terra-state", "crates/terra-control", "crates/terra-mobile", "crates/terra-motors","crates/terra-mapping", "crates/terra-transport", "crates/terra-waypoint"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
terra-actuators = { path = "crates/terra-actuators" }
terra-autonomy = { path = "crates/terra-autonomy" }
terra-navigation = { path = "crates/terra-navigation" }
terra-experiment = { path = "crates/terra-experiment" }
terra-types = { path = "crates/terra-types" }
terra-state = { path = "crates/terra-state" }
terra-control = { path = "crates/terra-control" }
terra-motors = { path = "crates/terra-motors" }
terra-mapping = { path = "crates/terra-mapping" }
terra-transport = { path = "crates/terra-transport" }
terra-waypoint = { path = "crates/terra-waypoint" }
uniffi = "=0.31.1"

[profile.dev]
debug = 0
[profile.release]
lto = "thin"
codegen-units = 1
