[package]
name = "terra-mobile"
version.workspace = true
edition.workspace = true
[lib]
crate-type = ["lib", "staticlib", "cdylib"]
[dependencies]
terra-actuators.workspace = true
serde = { version = "1", features = ["derive"] }
terra-autonomy.workspace = true
terra-navigation.workspace = true
terra-experiment.workspace = true
serde_json = "1"
terra-transport.workspace = true
terra-mapping.workspace = true
terra-types.workspace = true
terra-state.workspace = true
terra-control.workspace = true
terra-waypoint.workspace = true
uniffi.workspace = true
thiserror = "2"
[features]
bindgen = ["uniffi/cli"]
[[bin]]
name = "terra-bindgen"
path = "src/bin/bindgen.rs"
required-features = ["bindgen"]

[dev-dependencies]
zenoh = { version = "=1.10.1", default-features = false, features = ["transport_tcp"] }
