import Foundation
@main struct ConnectionLifecycleTests {
    static func main() {
        let a = UUID(), b = UUID()
        var p = TerraConnectionPolicy()
        p.begin(preferred: a)
        precondition(p.discover(.init(identifier: b, name: "terra-B", pairing: false)) == nil)
        precondition(p.discover(.init(identifier: b, name: "terra-B", pairing: true)) == .offer(b))
        precondition(p.discover(.init(identifier: b, name: "terra-B", pairing: true)) == nil)
        p.decline(b)
        precondition(p.discover(.init(identifier: b, name: "terra-B", pairing: true)) == nil)
        precondition(p.discover(.init(identifier: a, name: "terra-A", pairing: false)) == .connect(a))
        precondition(p.discover(.init(identifier: a, name: "terra-A", pairing: false)) == nil)
        p.failed(retryable: true, now: 10)
        precondition(!p.retryDue(now: 10.5)); precondition(p.retryDue(now: 11))
        precondition((0..<6).map { _ in p.nextRouterDelay() } == [1,2,4,8,15,15])
        let generation = p.generation
        p.stop()
        precondition(p.generation != generation && !p.retryDue(now: 100))
        p.begin(preferred: nil)
        precondition(p.discover(.init(identifier: b, name: "terra-B", pairing: true)) == .offer(b))
        p.accept(b, now: 0)
        precondition(!p.attemptExpired(now: 14)); precondition(p.attemptExpired(now: 15))
        p.paired(b, now: 20)
        precondition(p.preferred == b)
        precondition(p.discover(.init(identifier: b, name: "terra-B", pairing: true)) == nil)
        precondition(p.discover(.init(identifier: b, name: "terra-B", pairing: false)) == .connect(b))
        p.authenticated(b)
        precondition(p.connected == b)
        p.stop()
        precondition(p.discover(.init(identifier: a, name: "terra-A", pairing: true)) == nil)
        p.begin(preferred: nil)
        precondition(!p.adoptAuthenticated(a))
        precondition(p.connected == nil)
        p.begin(preferred: a)
        precondition(p.adoptAuthenticated(a))
        precondition(p.connected == a)
        var candidates = TerraPairingCandidates()
        candidates.observe(.init(identifier: a, name: "terra-A", pairing: true), now: 0)
        candidates.observe(.init(identifier: b, name: "terra-B", pairing: true), now: 1)
        candidates.observe(.init(identifier: b, name: "terra-B", pairing: false), now: 2)
        precondition(candidates.available(now: 2).map(\.id) == [a])
        precondition(candidates.available(now: 11).isEmpty)
        p.begin(preferred: nil); p.accept(a, now: 0); p.stop()
        precondition(p.attempting == nil && !p.enabled && !p.attemptExpired(now: 20))
        precondition(TerraBluetoothFailurePolicy.retryable("Bluetooth unavailable"))
        precondition(TerraBluetoothFailurePolicy.retryable("Bluetooth permission required"))
        precondition(!TerraBluetoothFailurePolicy.retryable("Malformed Bluetooth message"))
        precondition(!TerraBluetoothFailurePolicy.retryable("Encrypted read/notification failed"))
        precondition(TerraRouterSettings.parse(endpoint: "tcp/127.0.0.1:7448", prefix: "terra/phone", roverID: "7")?.roverID == 7)
        precondition(TerraRouterSettings.parse(endpoint: "tcp/[::1]:7448", prefix: "terra/phone", roverID: "0") != nil)
        for endpoint in ["", "tcp/:7448", "tcp/host:0", "tcp/host:7448:", "tcp/host:65536", "udp/host:7448"] {
            precondition(TerraRouterSettings.parse(endpoint: endpoint, prefix: "terra/phone", roverID: "7") == nil)
        }
        precondition(TerraRouterSettings.parse(endpoint: "tcp/host:7448", prefix: "terra/*", roverID: "7") == nil)
        precondition(TerraRouterSettings.parse(endpoint: "tcp/host:7448", prefix: "terra/phone", roverID: "-1") == nil)
        precondition(TerraManualRouterSafety.emergencyStopped(statusJSON: "{\"status\":{\"safety\":\"emergency_stop\"}}"))
        precondition(!TerraManualRouterSafety.emergencyStopped(statusJSON: "{\"status\":{\"safety\":\"hold\"}}"))
        precondition(!TerraManualRouterSafety.emergencyStopped(statusJSON: "{}"))
        print("Connection lifecycle: checks passed")
    }
}
